#!/usr/bin/env bash
# report.sh — Generate FAFCAS compliance report
# Usage: ./report.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENT_DIR="$(dirname "$SCRIPT_DIR")"
DONE_DIR="$AGENT_DIR/markers/done"
ANALYSIS="$DONE_DIR/analysis.jsonl"
REPORT="$DONE_DIR/report.md"
SUMMARY="$DONE_DIR/summary.json"

log() { echo "[$(date -Iseconds)] [report] $*" >&2; }

# FAFCAS dimensions with descriptions
declare -A DIMENSIONS=(
    ["factual"]="Claims backed by evidence"
    ["accurate"]="Correct technical assertions"
    ["fair"]="Balanced assessment"
    ["complete"]="All aspects reviewed"
    ["actionable"]="Specific next steps"
    ["specific"]="Exact locations cited"
)

calculate_score() {
    local dimension="$1"
    local count
    count=$(grep -c "\"dimension\":\"$dimension\"" "$ANALYSIS" 2>/dev/null | tr -d '[:space:]' || echo 0)
    [ -z "$count" ] && count=0
    
    # Fewer findings = higher score
    if [ "$count" -eq 0 ]; then
        echo 5
    elif [ "$count" -le 2 ]; then
        echo 4
    elif [ "$count" -le 5 ]; then
        echo 3
    elif [ "$count" -le 10 ]; then
        echo 2
    else
        echo 1
    fi
}

generate_stars() {
    local score="$1"
    printf '★%.0s' $(seq 1 "$score")
    printf '☆%.0s' $(seq $((score + 1)) 5)
}

log "Generating FAFCAS report..."

# Calculate scores
declare -A SCORES
for dim in "${!DIMENSIONS[@]}"; do
    SCORES[$dim]=$(calculate_score "$dim")
done

# Calculate averages
total=0
for score in "${SCORES[@]}"; do
    ((total += score))
done
avg=$((total / ${#SCORES[@]}))

# Generate report
cat > "$REPORT" << EOF
# FAFCAS Code Review Report

**Generated:** $(date -Iseconds)  
**Branch:** $(git branch --show-current 2>/dev/null || echo "unknown")

---

## Summary

| Dimension | Score | Assessment |
|-----------|-------|------------|
| Factual | ${SCORES[factual]} $(generate_stars ${SCORES[factual]}) | ${DIMENSIONS[factual]} |
| Accurate | ${SCORES[accurate]} $(generate_stars ${SCORES[accurate]}) | ${DIMENSIONS[accurate]} |
| Fair | ${SCORES[fair]} $(generate_stars ${SCORES[fair]}) | ${DIMENSIONS[fair]} |
| Complete | ${SCORES[complete]} $(generate_stars ${SCORES[complete]}) | ${DIMENSIONS[complete]} |
| Actionable | ${SCORES[actionable]} $(generate_stars ${SCORES[actionable]}) | ${DIMENSIONS[actionable]} |
| Specific | ${SCORES[specific]} $(generate_stars ${SCORES[specific]}) | ${DIMENSIONS[specific]} |

**Overall:** ${avg}/5 $(generate_stars "$avg")

---

## Findings

EOF

# Group findings by type
if [ -f "$ANALYSIS" ] && [ -s "$ANALYSIS" ]; then
    total_findings=$(wc -l < "$ANALYSIS")
    
    echo "### By Type" >> "$REPORT"
    echo "" >> "$REPORT"
    
    for type in $(cat "$ANALYSIS" | jq -r '.type' 2>/dev/null | sort -u); do
        count=$(grep -c "\"type\":\"$type\"" "$ANALYSIS" 2>/dev/null || echo 0)
        echo "- **$type**: $count finding(s)" >> "$REPORT"
    done
    
    echo "" >> "$REPORT"
    echo "### Details" >> "$REPORT"
    echo "" >> "$REPORT"
    
    while IFS= read -r finding; do
        file=$(echo "$finding" | jq -r '.file // "unknown"')
        line=$(echo "$finding" | jq -r '.line // 0')
        type=$(echo "$finding" | jq -r '.type // "unknown"')
        text=$(echo "$finding" | jq -r '.text // ""')
        severity=$(echo "$finding" | jq -r '.severity // 0')
        
        severity_icon="⚪️"
        [ "$severity" -ge 3 ] && severity_icon="🟡"
        [ "$severity" -ge 4 ] && severity_icon="🔴"
        
        echo "- $severity_icon \`$file:$line\` **$type**: $text" >> "$REPORT"
    done < "$ANALYSIS"
else
    echo "No findings." >> "$REPORT"
fi

echo "" >> "$REPORT"
echo "---" >> "$REPORT"
echo "*Report generated by code-review-agent*" >> "$REPORT"

# Generate summary JSON
cat > "$SUMMARY" << EOF
{
  "timestamp": "$(date -Iseconds)",
  "branch": "$(git branch --show-current 2>/dev/null || echo 'unknown')",
  "scores": {
    "factual": ${SCORES[factual]},
    "accurate": ${SCORES[accurate]},
    "fair": ${SCORES[fair]},
    "complete": ${SCORES[complete]},
    "actionable": ${SCORES[actionable]},
    "specific": ${SCORES[specific]}
  },
  "overall": $avg,
  "findings": $(cat "$ANALYSIS" 2>/dev/null | jq -s '.' || echo "[]"),
  "total_findings": $(cat "$ANALYSIS" 2>/dev/null | wc -l | tr -d '[:space:]' || echo 0)
}
EOF

log "Report generated: $REPORT"
log "Summary: $SUMMARY"
