#!/bin/bash
# Generate launch draft posts - Agent-powered

set -e

SCRATCH_DIR="scratchpad"
SCRATCH_FILE="drafts.md"
TIMESTAMP=$(date -Iseconds)

mkdir -p "$SCRATCH_DIR"

# Check for pi agent
if ! command -v pi >/dev/null 2>&1; then
    echo "❌ pi agent not found. Install from pi-coding-agent"
    exit 1
fi

# Check for context
if [ ! -f "context/targets.md" ]; then
    echo "❌ No context/targets.md found"
    exit 1
fi

echo "=== AGENT DRAFT GENERATION ==="
echo ""
echo "Reading targets..."
cat context/targets.md

# Build prompt
PROMPT=$(cat << 'PROMPT_END'
You are helping generate social media content for a product launch.

Read the targets from context/targets.md. Generate 3 distinct launch posts:

1. **Draft A (Hacker News)**: Technical, substantive, no marketing fluff
2. **Draft B (X/Twitter)**: Punchy, provocative, calls to action
3. **Draft C (Reddit)**: Helpful, educational, community-focused

For each draft:
- Write the actual post content (150-280 chars for X, longer for HN/Reddit)
- Include relevant hashtags
- Include the link: https://github.com/pjsvis/just-silo

Format your output as:

# Launch Drafts

## Draft A: Hacker News (Technical)
```
[your post content here]
```

## Draft B: X (Provocative)
```
[your post content here - punchy, provocative]
```

## Draft C: Reddit (Educational)
```
[your post content here - helpful, educational]
```

Keep the tone authentic. No hype. Just do it.
PROMPT_END
)

echo ""
echo "Generating drafts via pi agent..."
echo ""

# Call pi agent
# The -s flag silences the intro, -p is prompt
RESPONSE=$(pi -s -p "$PROMPT" 2>/dev/null)

# Write to scratchpad
cat > "$SCRATCH_DIR/$SCRATCH_FILE" << EOF
# Launch Drafts - $TIMESTAMP

$RESPONSE

---
*Generated by pi agent: $(date "+%Y-%m-%d %H:%M:%S")*
EOF

echo ""
echo "✅ Drafts generated: $SCRATCH_DIR/$SCRATCH_FILE"
echo ""
echo "Run 'just review' to see drafts via glow and approve"
