#!/bin/bash
# td-markdown-report.sh
# Generate markdown report from td database
# Usage: ./td-markdown-report.sh [output-file]

set -e

cd "$(dirname "$0")/.."
PROJECT_DIR="$(pwd)"

OUTPUT="${1:-td-report.md}"

# Generate report
{
  echo "# TD Task Report"
  echo ""
  echo "Generated: $(date)"
  echo "Project: $PROJECT_DIR"
  echo ""
  echo "## Summary"
  echo ""
  td info 2>/dev/null | grep -v "^$" | head -20 | sed 's/^/  /'
  echo ""
  echo "## Issues"
  echo ""
  td list --short 2>/dev/null | while IFS= read -r line; do
    # Parse: td-xxxxx  [Pn]  Title  type  [status]
    id=$(echo "$line" | awk '{print $1}')
    pri=$(echo "$line" | grep -oE '\[P[0-4]\]')
    # Remove status bracket for title
    title=$(echo "$line" | sed 's/\s*\[[a-z_]*\]$//' | sed 's/td-[a-f0-9]*  \[P[0-4]\]  //' | sed 's/  task  \|  feature  \|  epic  \|  bug  \|  chore  //')
    status=$(echo "$line" | grep -oE '\[open\]|\[in_progress\]|\[in_review\]|\[blocked\]|\[closed\]' | tr -d '[]')
    echo "| $id | $pri | $title | task | $status |"
  done
  echo ""
  echo "## In Review"
  echo ""
  if td in-review 2>/dev/null | grep -q "td-"; then
    td in-review 2>/dev/null | while IFS= read -r line; do
      echo "- $line"
    done
  else
    echo "  None"
  fi
  echo ""
  echo "## Blocked"
  echo ""
  if td blocked 2>/dev/null | grep -q "td-"; then
    td blocked 2>/dev/null | while IFS= read -r line; do
      echo "- $line"
    done
  else
    echo "  None"
  fi
  echo ""
  echo "---"
  echo "*Generated by td-markdown-report.sh*"
} > "$OUTPUT"

echo "Report generated: $OUTPUT"
